### ISSUE TITLE
Plot CrI3 magnon bands with DMI 

### ISSUE THREAD

**Issue by lisurui6** [SpinW/spinw#175]
Hi there, 

I am trying to use spinW to produce the monolayer CrI3 magnon bands using exchange parameters computed from TB2J. However, I am not getting the same results as that from TB2J. As I am inexperience in using spinW, any help is greatly appreciated. 

I first setup the crystal structure using only Cr atoms:
```
spinw.genlattice('lat_const',[6.823081 6.823081 13.83830157],'angled',[90 90 120], 'spgr', 0)

spinw.addatom('label','Cr3+','r',[1/3 1/3 1/2],'S', 3/2)

spinw.addatom('label','Cr3+','r',[2/3 2/3 1/2], 'S', 3/2, 'color', 'Red')
```

Then I add couplings of exchange, DMI and bilinear, using values from TB2J calculations. 
```
% We generate the list of bonds.

spinw.gencoupling('maxDistance', 30.2)

spinw.addmatrix('label','J12000','value', 0.41369799999999995)

spinw.addmatrix('label','D12000','value', [0 -1.15609e-08 -3.6807299999999996e-08;--1.15609e-08 0 6.568429999999999e-09;3.6807299999999996e-08 -6.568429999999999e-09 0])

spinw.addmatrix('label','B12000','value', [-0.176692 -0.018723 -7.0274e-06;-0.018723 -0.08646050000000001 -0.0260207;-7.0274e-06 -0.0260207 -0.280931])

spinw.addcoupling('mat','J12000','bond', 1, 'subIdx', 1)

spinw.addcoupling('mat','D12000','bond', 1, 'subIdx', 1)

spinw.addcoupling('mat','B12000','bond', 1, 'subIdx', 1)

 
spinw.addmatrix('label','J11010','value', 0.8650319999999999)

spinw.addmatrix('label','D11010','value', [0 -0.011737 -0.010856600000000001;--0.011737 0 -0.00548058;0.010856600000000001 --0.00548058 0])

spinw.addmatrix('label','B11010','value', [-0.137607 -0.00916113 -0.0117692;-0.00916113 -0.23676399999999997 -0.00368631;-0.0117692 -0.00368631 -0.156384])

spinw.addcoupling('mat','J11010','bond', 4, 'subIdx', 2)

spinw.addcoupling('mat','D11010','bond', 4, 'subIdx', 2)

spinw.addcoupling('mat','B11010','bond', 4, 'subIdx', 2)

....
Repeat for more NNs
```

Finally I plot the magnon bands along G M K G (not sure why but hermit has to be set to false here) 

```
Qlist = {[0 0 0] [1/2 0 0] [1/3 -1/3 0] [0 0 0] 100};

Qlab  = {'\Gamma' 'M' 'K' '\Gamma'};

spinw.genmagstr('mode','direct', 'k',[0 0 0],'n',[0 0 1],'S',[0 0; 0 0; 3 3]);

spec = spinw.spinwave(Qlist, 'hermit', false);

sw_plotspec(spec, 'qlabel', Qlab, 'mode', 1, 'colorbar', false, 'colormap', [0 0 0], 'dashed', true, 'legend', false)
```

But this is the magnon bands I got:
<img width="600" alt="image" src="https://github.com/SpinW/spinw/assets/17573510/7d347c23-5b7d-469f-b1cc-92317707dc21">

Comparing to TB2J bands:
<img src="https://github.com/SpinW/spinw/assets/17573510/cdfd9229-70c2-4506-8287-79f4d82016f7" alt="image" width="600" height="auto">

Any idea what I did wrong?

I am not so sure about the symmetry, which I set to 0, since I have defined all the atoms in a unit cell already. And I am not so sure about supercell, and if I need to define one and how (a 7X7 supercell was used in TB2J exchange params (i.e. (3, 3, 0) to (-3, -3, 0))). Not so sure about how DMI is set is either. But even with just exchange J and B, the number of bands are still different. (With J only, the bands are the same). 

Thanks so much in advance for your time.

**Comment by mducle** [comment]
@lisurui6 - the bands looks quite similar to me. The main differences are:

* In the SpinW plot, there is only 4 bands (2 magnon creation / positive energy, 2 magnon anihilation / negative energy), whilst in the TB2J there are more - this is because you've defined the SpinW model to have only 1 unit cell with 2 atoms - in spin wave theory you can only get 2 bands (one magnon creation, one magnon anihilation) per magnetic ion in the unit cell. I presume the extra bands in the TB2J plot is due to using a supercell (if you used a 7x7 super cell there should in principle be 196 bands (=49*4) but many of them would be degenerate. Even if you defined a 7x7 supercell in SpinW I don't think you will get the same plot as TB2J because your magnetic structure is just ferromagnetic so effectively would reduce back to a single cell (e.g. SpinW would calculate 196 bands but they would be degenerate to the 4 you've already seen) - you would need to define the moments in each cell of the super cell to be slightly different to get the bands to not be degenerate - if you can get a magnetic structure from TB2J you can then input this into SpinW and maybe get a similar number of bands.

* The energy scale or bandwidth is slightly different (it looks a little lower in TB2J than SpinW) - this is probably due to the definition of the spin length (the `'S'` parameter in `addatom`). The magnon energy is proportional to `J*S` - in the SpinW model you've defined `S=1.5` whereas I presume that the TB2J calculation would have used a calculated ordered moment which would be slightly less than `1.5` - you can just change the `'S', 3/2` part of the `addatom` command to scale the overall bandwidth - maybe something like `'S', 1.35` would give you something closer to what TB2J calculates - if TB2J outputs the calculated ordered moment on each site you can put that into the SpinW calculation to get better agreement.
