### ISSUE TITLE
General 4th order term

### ISSUE THREAD

**Issue by mkmk0324** [SpinW/spinw#197]
In #95 and #152 you explain how to write interactions using the biquadratic form, is it possible to extend the input to a more general form?

i.e.,

![\sum_{i,j}({\bf S}_iA_i{\bf S}_i)({\bf S}_jB_j{\bf S}_j)](https://latex.codecogs.com/png.image?\dpi{150}\sum_{i,j}({\bf%20S}_iA_i{\bf%20S}_i)({\bf%20S}_jB_j{\bf%20S}_j))

Is it possible to add a 4th order term of the form?

**Comment by mducle** [comment]
@mkmk0324 I think equations of this form is not possible with linear spin wave theory as implemented in SpinW - because we have to write the Hamiltonian in terms of the boson operators and we can only include terms which are quadratic in sites i and j in these operators. The reason that the (Si.Sj)^2 term works is because it involves only the on-diagonal terms which mostly yields quadratic terms or terms which are of the form (ai.ai^dagger)(aj.aj^dagger) which are just constants - there are also some quartic and higher order cross-terms (ai.aj.ai.aj etc) which end up being ignored in the linear approximation. In your case, I think the off-diagonal terms will _only_ involve terms higher order in the boson operators which we cannot express in linear spin wave theory. 

If you need to use these Hamiltonian terms I think you have to use a different code such as [Sunny](https://github.com/SunnySuite/Sunny.jl) which uses a generalisation of spin wave theory as its formulism, or an RPA code such as [McPhase](https://mcphase.github.io/webpage/).
