### ISSUE TITLE
Dmin is 0?

### ISSUE THREAD

**Issue by ovilella14** [SpinW/spinw#48]
I'm writing a script for a triangular lattice. I want to be able to specify each J bond in the lattice; all of them different. So I basically created an array of atoms the size of which depends on the size of the cell I want to see, so that I can create the bond between all of these atoms individually. But when I try to use gencoupling, my dmin = 0; I can't create the bonds. 

I'm not sure how challenging this issue is, but I looked through the documentation and couldn't find anything like it. 

Thank You

**Comment by Fellow-baka** [comment]
Would be cool to see a minimal working example of the code.

**Comment by ovilella14** [comment]
I'm sorry! Of course I'll drop the file.
Basically I'm trying to override the description of the unit cell, if that makes sense.
[randomJ.zip](https://github.com/SpinW/spinw/files/5613280/randomJ.zip)

**Comment by Fellow-baka** [comment]
If u want to access individual bonds you could try to use 'subIdx' in the .addcoupling by creating the cell by standard means.
Will it solve your problem?

**Comment by ovilella14** [comment]
I'm about to try it! Thank you, I'm really new to spinw so I'm not up on all the documentation yet.

**Comment by ovilella14** [comment]
So it doesn't seem to work because no matter how much I fiddle with it I can assign the bonds between two atoms at a time. It always repeats the pattern between more atoms. I'll keep playing with it though because like I said I'm pretty new to this so maybe there's a way I can use 'subIdx' more specifically.

**Comment by mducle** [comment]
@ovilella14 So the problem is that you're putting the atoms at equivalent lattice coordinates (SpinW uses a periodic cell) so coordinates like `(0,0,0)` and `(1,0,0)` or `(0,1,0)` are equivalent positions. When `gencoupling` tries to determine the neighbours of an atom it finds all these equivalent positions with which in the first unit cell are on top of each other and have `dmin=0`. Hence the error. 

I'm guessing that you have some sort of disorder in you system and you want to model it by putting in random bonds within some *supercell*. In SpinW you have to do this manually - e.g. for the 2 x 2 x 1 supercell you have in your script you need to use something like:

```
tri.genlattice('lat_const',[x y/sqrt(3) z].*latYMGO,'angled',[90 90 90])
```

then in the coordinate generation, divide through by these values (e.g. use `[i/x, j/y/ 0/z]` instead of `[i, j, 0]`). Essentially you have to make sure every coordinate in your `dims` array is less that one. It does mean that the `h` and `k` indices in the supercell is going to be 1/2 of the actual cell - so when you calculate the spinwave mode at (1/2, 1/2, 0) you're actually calculating it at (1/4, 1/4, 0) indexed in your original cell. 

There's an alternative, which is to use the `newcell` function but I haven't used it much myself so I can't tell you much about it.

**Comment by ovilella14** [comment]
Thank you! this helps so much
