### ISSUE TITLE
Inquiry about spin quantum number S

### ISSUE THREAD

**Issue by kkang14** [SpinW/spinw#54]
Dear SpinW team,

Hope you all stay well and healthy.
I want to ask about spin quantum number S.
I have a hard time addressing the spin quantum number S.

I used the same Jij value to calculate the magnon dispersion curve of Cr2Al with two different codes, SpinW and UPPASD.
The trend of curves agrees between the two codes. However, the magnitude is around 2.5 times different.
You can find the figure below.
https://drive.google.com/file/d/1cEHSx9xB79MuZyQwo_FgH4_wJYLjmTW5/view?usp=sharing

UPPASD does not need any spin quantum number, while SpinW needs it.
Thus, it seems this discrepancy comes from the unit of Jij or this number.
Both codes use linear spin-wave theory. I am not sure why input is different.
If you know anything, would you be able to answer this question?

Also, what is the unit of Jij?
I used SPRKKR to calculate Jij values with a unit of [meV].
Is it an appropriate unit? Is there any spin or magnetic moment unit in it?

And, how can we determine the spin quantum number?
If you don't mind, would you be able to share experience on how to choose the spin quantum number?
When I check "magion.dat" file, it seems there is a connection between charge and spin quantum number.
I used Bader charge analysis to get the charge state.
Is it the same charge comparing to the charge in "magion.dat"?

Thank you in advance!

Yours Sincerely,
Kisung Kang

Graduate Research Assistant, Ph. D. Candidate
Schleife group and Cahill group
Department of Materials Science and Engineering
University of Illinois at Urbana Champaign

**Comment by Fellow-baka** [comment]
Some differences in definitions between UPPASD and SpinW were discussed also here https://groups.google.com/g/spinwforum/c/zZUwZcWf0io

**Comment by kkang14** [comment]
Thank you for your reply!
I am still confused with the S value.

Does a classical calculation always assume S=3/2? Or Does it depend on the element?
In my case, the difference is about 3.15 times. I am not sure how it is connected to this S value.
Should I need to think of a spin quantum number of elements with neutral charge?

Yours Sincerely,
Kisung Kang

**Comment by Fellow-baka** [comment]
> Also, what is the unit of Jij?
It is a [meV], but sometimes it differs by a factor of 1/2 depending on Hamiltonian notation.
>  Is it an appropriate unit? Is there any spin or magnetic moment unit in it?
Yes. No, as far as I know.
> And, how can we determine the spin quantum number?
You can use an arbitrary one (check the help for spinw/addatom).

For your particular system, I guess, it should be low- or high- spin state of Cr, like 1 or 3/2.
But, I think, it should be exactly known from the magnetization or neutron scattering experiments.

**Comment by mducle** [comment]
Thank @Fellow-baka for answering some of this.

@kkang14 :

> what is the unit of Jij?

There are some assumptions in the code that it is in [meV] but in principle it can be whatever you want. If you don't use an applied magnetic field (which is assumed to be in Tesla, and converted to meV), then whatever energy unit you use for Jij (and the single-ion aniosotropy - they must be the same unit) will be the unit of the output spin wave energies. 

> I want to ask about spin quantum number S.

This is basically a "convenience" for users. Essentially the spin wave energy depends on the product J*S - a larger exchange interaction J or a larger total spin S will yield a larger spin wave energy (or dispersion bandwidth). I think this energy dependence is linear in S rather than in S^2 or S(S+1) as Sandor said in the forum post. In some of the literature, "J" actually means J*S and the "S" value is ignored. You can also do this - just set "S" to "1" in the input to `addatom` and use the values of J you calculate from the KKR method. (PS. Also despite what Sandor said about the quantum mechanical nature of the spins, as far as *linear* spin wave theory is concerned you only have an effective two-level system and the total spin S doesn't come into the calculation except to scale the dispersion as noted above - the S states are not used in the calculation which treats the spins as a semi-classical vector quantity).

The idea behind "S" is because spin wave theory grew out of the localised moment picture, where the localised spins have definite half-integral total spin S. This depends on the number of electrons in the outer shell or equivalently the ionic valence (and it's assumed that all the electrons formally in that shell are localised on the ionic site and so contribute to the total spin S). Now, this picture doesn't really mesh with the band-structure / electronic structures type picture where electrons can be delocalised away from the ionic site. (Also, the formal valence we're talking about here is *not* the actual ionic charge calculated from electronic structures calculation - the formal valence is always integral). 

> Does a classical calculation always assume S=3/2? Or Does it depend on the element?

It depends on the ion (element and formal valence state). I assume you have Cr3+ ions which has 3 electrons in the d-shell and so has a total (formal) spin S=3/2. Cr2+ would have 2 electrons and S=1, whilst Mn3+ would have 4 electrons and S=2. 

> In my case, the difference is about 3.15 times. I am not sure how it is connected to this S value.

I'm not sure what this `3.15` means? Is it the difference between the UPPASD and SpinW calculation?

I think that a difference could be that SpinW defines the spin Hamiltonian without the factor of 1/2 for double counting. So, I think to convert it to some convention in the literature you might have to multiply the exchange J you use in the other program by 2*S (2 * 1.5 in this case) to use in SpinW.

**Comment by kkang14** [comment]
Thank @mducle for your comments!

Your explanation helps me a lot. I understand the dispersion bandwidth is linearly proportional to S value.
I still have some inquiries about this.

One thing I am always confused about is the definition of S value.
It seems people sometimes mean this as a spin quantum number while the others said this is total spin.
Does total spin mean the magnetic moment on a magnetic atom?
For example, for Cr2Al case, Cr atom has a 1.31 μB moment.
I knew spin quantum number is expressed by half-integers.

When we study any materials, how can we define the charge state of ions or S value?
Here, I couldn't define the charge state of Cr and Al in Cr2Al. That is huge trouble when I calculate magnon dispersion.
I knew there are some ways to define S value by the temperature dependence of net magnetization or neutron scattering.
If we don't have this kind of information, how can we define S value?

Another inquiry is about a comparison between UPPASD and SpinW results.
So far I tested several materials such as MnPt, CuMnAs, Mn2Au, and Cr2Al.
I always used S=1 for Mn or Cr atoms.
I haven't seen any discrepancy between both codes for MnPt, CuMnAs, Mn2Au cases.
However, Cr2Al shows a large difference. As I mentioned above, the ratio between the results of UPPASD and SpinW is about 3.15.

Cr+3 and double counting can explain this discrepancy.
However, in that case, I also need to apply this to other materials.
Then, now previous materials MnPt, CuMnAs, Mn2Au suffer the difference.
How can I address this problem?

Yours Sincerely,
Kisung Kang

**Comment by mducle** [comment]
@kkang14 

> One thing I am always confused about is the definition of S value.

In principle it is the total spin quantum number (e.g. the sum of the electron spins of that ion). Also, in principle, if you have a fully localised ion, the magnetic moment in uB is gS where g=2. But for itinerant systems you've probably got moment reductions due to various reasons. 

I think for your purposes, you should probably ignore S (set it to 1). 

The discrepancy you mention only Cr2Al vs the other compounds is a bit strange, though. If in the other compounds SpinW and UPPASD agree then I would also expect Cr2Al to agree - it would suggest that the double counting factor is not the issue and the since you've set S=1 in both cases S is also not the issue. Unfortunately, I've never used UPPASD, so I can't tell you if it handles Cr any differently... Do you have to specify the ion type in an UPPASD calculation? If so, what if you use the model for Cr2Al but use Mn instead Cr as the magnetic species? If this changes the UPPASD dispersion then it suggests that UPPASD is applying an internal scaling depending on the magnetic ion...

**Comment by kkang14** [comment]
Thank @mducle for a quick answer.

> Do you have to specify the ion type in an UPPASD calculation? If so, what if you use the model for Cr2Al but use Mn instead Cr as the magnetic species? If this changes the UPPASD dispersion then it suggests that UPPASD is applying an internal scaling depending on the magnetic ion...

There are two different things between UPPASD and SpinW.
UPPASD does not specify the element for each atom.
And the magnon dispersion depends on the magnetic moment on each atom instead of assigning S value.
It seems the discrepancy might originate from the different definitions of Jij Si Sj on both codes.
Could Jij ei ej affect the results? Here ei and ej are unit vectors of magnetic moments on atom i and j.

**Comment by kkang14** [comment]
@mducle 
This still does not solve the problem.
I think I need to check what is going on in UPPASD.
Thank you so much for your comments!
