### ISSUE TITLE
eig_omp crashes matlab

### ISSUE THREAD

**Issue by pastle** [SpinW/spinw#62]
It seems that matlab often crashes under a continuous execution of the 'eig_omp' mex function. For example, when running the following command:

> for ind = 1:1e6
>     mat = randi(5,[4, 4, 6e3])+1j*randi(5, [4,4,6e3]);
>     [ev, ed] = eig_omp(mat);
> end

matlab will crash at ind ~ 9000. Maybe there is some memory leakage? Is there any easy fix for this problem? 

(My mex file was compiled in Matlab_2021a using MinGW. The system has 16G RAM and 8 cpus.)

**Comment by mducle** [comment]
@pastle Yes, there's been a problem with the code is R2017(ish) when Matlab changed the C API - it's not been supported since then (we changed the m-file code to disable using the mex files).

We haven't updated the code due to time shortage and because the longer term plan is to translate the computation core of SpinW to C++ to allow a transition to Python. Unfortunately there is currently little effort available for this also.

**Comment by pastle** [comment]
Hi Duc, thanks for the explanations. At the moment, I can divide the full loop into shorter segments and run them one by one.

**Comment by mducle** [comment]
@pastle Ok - if you like, but please check the accuracy of your final calculation with the "no mex" (pure-Matlab) code - one reason we disabled using the mex files in the Matlab code is because in certain cases (especially for complex Hamiltonian matrices) it gives incorrect results.
